version: "3.7"
services:
   mysql:
      image: mysql:8
      command: --default-authentication-plugin=mysql_native_password
      container_name: mysqld
      environment:
         - MYSQL_ROOT_PASSWORD=cTg8HwBmRT54GCQmNyuKgHrq
         - MYSQL_USER=prestashop
         - MYSQL_PASSWORD=SGmTU54u6sf6QEc2MrKdq74U
         - MYSQL_DATABASE=prestashop
      volumes:
         - ./permanent/mydata:/var/lib/mysql:rw
      ports:
         - 3306:3306
   prestashop:
      build: .
      container_name: prestashop
      ports:
         - 8000:80
      links:
         - mysql:dbhost

