#!/bin/bash
#
# The entrypoint of the container.

USERID=${UID:-1000}

# Init the django environments
init()
{
   echo "Initializes the envirnonment..."
}

run()
{
   init
   echo "Going to execute the server ...."
   /usr/bin/supervisord -c /scripts/supervisord.conf
}


ctl()
{
   echo "Going to execute the supervisorctl command: \"$@\"..."
   supervisorctl -c /scripts/supervisord.conf ${*:2}
}

finalizes()
{
   echo "Finalizes the installation..."
   ADMIN=`find /usr/share/nginx/html -type d -regex ".*admin[0-9a-z]*\$" -maxdepth 1`
   ADMIN=`basename $ADMIN`
   echo "  Rewrite the admin directory to $ADMIN..."
   sed -i "s|# ADMIN-REWRITE|location /$ADMIN/{\n\t\tif (\!-e \$request_filename) {\n\t\t\trewrite ^/.*\$ /$ADMIN/index.php last;\n\t\t}\n\t}|g" /scripts/nginx.conf
   echo "  Removing the installation directory..."
   rm -rf /usr/share/nginx/html/install
}

printhelp()
{
   echo "This entrypoint support belows commands:"
   echo "  init             - Init the Django environment and install the dependencies;"
   echo "    Usage: init"
   echo "  run              - Startup the service with supervisor daemon;"
   echo "    Usage: run"
   echo "  status           - Showing the status of supervisord;"
   echo "    Usage: status"
   echo "  ctl              - Execute the [supervisorctl command](http://supervisord.org/running.html#running-supervisorctl);"
   echo "    Usage: ctl <action> <program>"
   echo "  finalizes        - Finalizes the installation;"
   echo "    Usage: finializes"
   echo "  help             - Print this help message"
   echo "    Usage: help"
}


case "$1" in
   init)
      init "$@"
      ;;
   run)
      run "$@"
      ;;
   ctl)
      ctl "$@"
      ;;
   status)
      ctl "status"
      ;;
   finalizes)
      finalizes
      ;;
   help)
      printhelp
      ;;
   *)
      echo "Executing runtime command \"$@\"..."
      exec "$@"
esac
